name: Build

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  AUTHENTICATION: authentication
  IMAGE_NAME: ${{ github.repository }}
  ACTIONS_STEP_DEBUG: true

jobs:
  publishKinnaj:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker duildx
        uses: docker/setup-buildx-action@v2
      - name: log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE }}
      - name: extract metadata (tags, labels) for kinnaj
        id: kinnaj
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
      - name: build and push docker image kinnaj to ghcr.io
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "CONFIGURATION=production"
          push: true
          tags: ${{ steps.kinnaj.outputs.tags }}
          labels: ${{ steps.kinnaj.outputs.labels }}